# Window Settings

[font]
    normal =                                { family = "JetBrainsMono Nerd Font", style = "Regular" }
    size = 10

[window]
    padding.x =                             12
    padding.y =                             12

# Colours Settings 

[colors.primary]
    background =                            '#1F1F1F'
    foreground =                            '#E6E6E9'
    dim_foreground =                        '#E6E6E9'
    bright_foreground =                     '#E6E6E9'

[colors.normal]
    black   =                               '#141414'
    red     =                               '#8BAAAD'
    green   =                               '#E6E6E9'
    yellow  =                               '#F9E2AF'
    blue    =                               '#9999A1'
    magenta =                               '#E6E6E9'
    cyan    =                               '#F4F4F6'
    white   =                               '#F2F8F8' 

[colors.bright]
    black   =                               '#9999A1'
    red     =                               '#8BAAAD'
    green   =                               '#E6E6E9'
    yellow  =                               '#F9E2AF'
    blue    =                               '#9999A1'
    magenta =                               '#E6E6E9'
    cyan    =                               '#F4F4F6'
    white   =                               '#F2F8F8' 

[colors.dim]
    black   =                               '#45475A'
    red     =                               '#8BAAAD'
    green   =                               '#E6E6E9'
    yellow  =                               '#F9E2AF'
    blue    =                               '#9999A1'
    magenta =                               '#E6E6E9'
    cyan    =                               '#F4F4F6'
    white   =                               '#F2F8F8'


# Miscellaneous

[colors.search.matches]
    foreground =                            '#A6ADC8'
    background =                            '#1E1E2E'

[colors.search.focused_match]
    foreground =                            '#A6E3A1'
    background =                            '#1E1E2E'

[colors.hints.start]
    foreground =                            '#F9E2AF'
    background =                            '#1E1E2E'

[colors.hints.end]
    foreground =                            '#A6ADC8'
    background =                            '#1E1E2E'

[colors.cursor]
    text =                                  '#F5E0DC'
    cursor =                                '#FFFFFF'  

[colors.vi_mode_cursor]
    text =                                  '#B4BEFE'
    cursor =                                '#1E1E2E' 

[colors.footer_bar]
    foreground =                            '#000000'
    background =                            '#21bdff'

[colors.selection]
    text =                                  '#000000'
    background =                            '#FFFFFF'



