# Window Settings

[font]
normal = { family = "RobotoMono Nerd Font", style = "Regular" }
bold = { family = "RobotoMono Nerd Font", style = "Bold" }
italic = { family = "RobotoMono Nerd Font", style = "Italic" }
bold_italic = { family = "RobotoMono Nerd Font", style = "Bold Italic" }
size = 9

[window]
    padding.x =                         9
    padding.y =                         9

# Colours Settings 

[colors.primary]
    background =                        '#f8fbf8'
    foreground =                        '#333333'
    dim_foreground =                    '#696969'
    bright_foreground =                 '#ffffff'

[colors.normal]
    black   =                           '#333333' 
    red     =                           '#cd0000' 
    green   =                           '#0fb300'
    yellow  =                           '#ffa500'
    blue    =                           '#0000ff'
    magenta =                           '#ba36a5'
    cyan    =                           '#21bdff'
    white   =                           '#a9a9a9'

[colors.bright]
    black   =                           '#333333'
    red     =                           '#ffe6e4'
    green   =                           '#ccffcc'
    yellow  =                           '#fff68f'
    blue    =                           '#e5f4fb'
    magenta =                           '#ffe4ff'
    cyan    =                           '#e0ffff'
    white   =                           '#686868'

[colors.dim]
    black   =                           '#f8fbf8'
    red     =                           '#cd0000'
    green   =                           '#0fb300'
    yellow  =                           '#ffa500'
    blue    =                           '#0000ff'
    magenta =                           '#ba36a5'
    cyan    =                           '#21bdff'
    white   =                           '#686868'



# Miscellaneous

[colors.search.matches]
    foreground =                        '#000000'
    background =                        '#fef69f'

[colors.search.focused_match]
    foreground =                        '#000000'
    background =                        '#ffa500'



[colors.hints.start]
    foreground =                        '#85ceeb'
    background =                        '#fef69f'

[colors.hints.end]
    foreground =                        '#000000'
    background =                        '#a9a9a9'



[colors.footer_bar]
    foreground =                        '#000000'
    background =                        '#21bdff'



[colors.selection]
    text =                              '#000000'
    background =                        '#8ed3ff'



[colors.cursor]
    text =                              '#ffffff'
    cursor =                            '#ffb6b6'  

[colors.vi_mode_cursor]
    text =                              '#ffffff'
    cursor =                            '#ba36a5' 
